version: "3.4"

services:
  db:
    image: mysql:5.7
    ports:
      - '13306:3306'
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=from_db
      - MYSQL_ROOT_PASSWORD=pass
      - TZ=Asia/Tokyo

  embulk:
    image: ietty/embulk
    volumes:
      - ./liquid:/liquid:cached
    links:
      - db
    environment:
      - TZ=Asia/Tokyo
    depends_on:
      - db
