version: "3.4"

services:
  from_db:
    image: mysql:5.7
    ports:
      - '13306:3306'
    volumes:
      - from_db-volume:/var/lib/mysql
    environment:
      - ./mysql/from_db/init.sql:/docker-entrypoint-initdb.d
      - MYSQL_ROOT_PASSWORD=pass
      - TZ=Asia/Tokyo

  to_db:
    image: mysql:5.7
    ports:
      - '23306:3306'
    volumes:
      - to_db-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - TZ=Asia/Tokyo

  embulk:
    tty: true
    build:
      context: .
    volumes:
      - ./liquid:/liquid
    links:
      - from_db
      - to_db
    environment:
      - TZ=Asia/Tokyo

volumes:
  from_db-volume:
  to_db-volume:
