name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run a embulk
      run: |
        docker-compose up --build -d
        docker-compose exec embulk sh -c "embulk preview /liquid/_config.yml.liquid"
        docker-compose exec embulk sh -c "embulk run /liquid/_config.yml.liquid"
