name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run a embulk
      run: |
        docker-compose build
        docker-compose run embulk sh -c "sleep 3 && embulk preview /liquid/_config.yml.liquid"
        docker-compose run embulk sh -c "sleep 3 && embulk run /liquid/_config.yml.liquid"
